from .appointment import AppointmentSchema
from .appointment import AppointmentSchemaNested
from .gender import GenderSchema
from .machine import MachineSchema
from .machineAndRegion import MachineAndRegionSchema
from .maintenance import MaintenanceSchema
from .maintenance import MaintenanceSchemaNested
from .patient import PatientSchema
from .priority import PrioritySchema
from .region import RegionSchema
